### ISSUE TITLE
可否考虑增加遍历渲染文件夹的功能？

### ISSUE THREAD

**Issue by fenqin** [jakwings/Siii#1]
偶然发现Siii，发现这个实在太棒了。
直接写好丢到网站就可以了。而且还支持`Markdown`，不能更赞了。
对我这样的懒人Siii比Hexo更有诱惑力啊= =。
但是，每次写一篇文章，都需要在配置文件里指定文件名。
然后才能开始写md源文件，这样太麻烦了。

恳请增加一个遍历渲染文件的功能。

**Comment by jakwings** [comment]
是么，Hexo 的主题很多啊，等你想要漂亮的主题时就惨啰……

自行配置文件名是想随时隐藏文章或是在不同分类摆同样的文章，
不过好像也可以改成在文章里指定位置，只是不太方便数据库读取。

Σ(っ °Д °;)っ 遍历渲染文件？同学你是不是忘了什么？
Siii 是动态博客，不像 Hexo 那样改一改就重新生成一大堆文件。我设计时就是这么想的。

**Comment by jakwings** [comment]
遍历渲染是可能的，抓取生成的 RSS 或 sitemap 里的所有 URL，用工具逐一访问就好了（在自己的电脑里做会快一些）。

**Comment by fenqin** [comment]
啊嘞，可能是我描述有误= =||

---

比如现在配置是这样的
```
2015-01-11 11:11:11+0800 //title1 //2016/01-11
demo1
%
2015-01-12 12:12:12+0800 //title2 //2016/01-12
demo2
```
我需要在这里配置好，然后再新建md文件。
每一篇文章都需要两步。

可不可以在配置里直接指定一个文件夹

```
1111-01-11 11:11:11+0800 ////2016/
```
这样每次写好md直接丢进2016这个文件夹
标题，描述，时间，可以在md文件里指定。
(｡･ω･) 这样可不可行

**Comment by jakwings** [comment]
原來如此啊。
我看这周有没时间改一下吧，顺便把 markdown 模块也更新一下。

**Comment by jakwings** [comment]
新的系统在 https://github.com/jakwings/Siii/tree/siii2

文章中的所有 `^/` 在转换为网页内容时都会被替换成博客路径（如 `/blog/`），方便随时更改位置而不必更改相关链接。
同时，多了几种配置博文分类的模式，看看配置文件便知了。
由于个人太懒，直接把自己用的主题模板改了下就扔上去了。O_O

**Comment by fenqin** [comment]
clone下来直接报500错误 (￣(エ)￣)

然后qiniu文件夹里塞得是神马啊=。=
我还纳闷怎么突然这么大了....

最后，真神速
`ORZ`

**Comment by jakwings** [comment]
qiniu 里放的是演示用的文件，包括一个 6M 的 mp4……
分类模式啥的主要是配合主题模板用的，两年前就私底下实现了。

你改好配置了吗，尤其是那个 path。
用的操作系统和 PHP 版本是啥？Windows 我没测试过。

**Comment by fenqin** [comment]
本地路径已经修改过了
环境是Linux+PHP 5.4

**Comment by jakwings** [comment]
改过路径后有没有删掉 .htaccess？
错误页面写着什么？空白？
apache2 服务器有没有提供 URL 重写模块（对应 .htaccess 中的 mod_rewrite）？

**Comment by fenqin** [comment]
1.Siii根目录下没有.htaccess文件
2.服务器错误 500
3.有的，原来的版本正常。

**Comment by fenqin** [comment]
妹的，手抖点错了

**Comment by jakwings** [comment]
真奇怪呢……你看看 apache2 的错误日志文件有没提示？

**Comment by jakwings** [comment]
你重新 clone 看看，好像是一个不兼容 php5.4 的语法导致的，另外我还修了一个小 bug。

**Comment by fenqin** [comment]
PHP Fatal error:  Can't use function return value in write context in ....../Siii/utils/siii.php on line 227

应该是这个错误导致的

**Comment by jakwings** [comment]
嗯，就是指那个语法错误，因为 `empty()` 只允许用在变量上。新版 php 改良了。

**Comment by fenqin** [comment]
发现现在的这个版本已经OK了
神速
再次ORZ

**Comment by jakwings** [comment]
啊，不小心改出另一个 bug →_→

详情看这里：https://github.com/jakwings/Siii/commit/34f0c6757193c6718244e2a75e42fe948b698887

**Comment by fenqin** [comment]
然而我看不懂 _(:з」∠)_
只是可别再出问题了 23333
我赶紧丢到网站上去    0.0

**Comment by jakwings** [comment]
好吧，把那个文件的那一行改成绿色背景那行的样子就行了。

这样偏向程序员的博客系统都能被你看上也是不容易，我想我该做个调查问卷。希望你不会太折腾吧……

**Comment by fenqin** [comment]
有个BUG，如果文件夹中有多个文件，不会解析成多个文章,而是一个文章包含了全部内容。

**Comment by jakwings** [comment]
OK, 已修复：https://github.com/jakwings/Siii/commit/2829560e09d3cf7869011008fd9a1b32a6b8e2f3

**Comment by fenqin** [comment]
简直了，直接复制你的文本保存一个新文件
会解析成这样
```
 今天是个好日子

2016-01-11T20:04:06+08:00 // 今天是个好日子

好久没吃过冰淇淋了。

%

于是到冰柜里拿了一根。

```
折腾了好长时间才发现是行结束标志惹的祸= =||

一样的内容，第一个就会不正常。
```
$ file article-01.md
article-01.md: UTF-8 Unicode text, with CRLF line terminators
$ file article-02.md
article-02.md: UTF-8 Unicode text
```

**Comment by jakwings** [comment]
稍微改一下就兼容 CRLF 了：https://github.com/jakwings/Siii/commit/4fdd871a1d2af4b146cdfe4ffa979868150e08e3
